version: '3.7'

services:
  ticket:
    container_name: boardgame-ticket
    image: elvinfeng/boardgame:ticket
    restart: always
    build:
      context: .
    labels:
    - traefik.enable=true
    - traefik.http.routers.ticket.rule=Host(`ticket.elvinfeng.com`)
    - traefik.http.routers.ticket.tls=true
    - traefik.http.routers.ticket.tls.certresolver=lets-encrypt
    - traefik.port=80
    networks:
    - traefik_proxy
    # ports:
    # - "80:80"

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge